name: expiry_mate
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

flutter_intl:
  enabled: true
  class_name: Language
  main_locale: zh
  output_dir: lib/gen

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  date_format: ^2.0.9
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flex_color_scheme: ^8.1.1
  flutter_dismissible_tile: ^1.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  objectbox_generator: ^4.1.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/language/
  fonts:
   - family: ABeeZee
     fonts:
       - asset: assets/fonts/ABeeZee-Regular.ttf
       - asset: assets/fonts/ABeeZee-Italic.ttf
         style: italic


