// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'db/data/food_collection.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1703458862176656042),
      name: 'FoodCollection',
      lastPropertyId: const obx_int.IdUid(11, 4793971275281203512),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8971254639589330985),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 401704908366773315),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 504877015282192482),
            name: 'productionDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6627372625428995582),
            name: 'safeguardDay',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 7010430439051640251),
            name: 'category',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6733119755010236047),
            name: 'expiredDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4793971275281203512),
            name: 'reminderDays',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1703458862176656042),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        8178031381453831784,
        7698965590161338805,
        6451520587619713678,
        6917913852055480676
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    FoodCollection: obx_int.EntityDefinition<FoodCollection>(
        model: _entities[0],
        toOneRelations: (FoodCollection object) => [],
        toManyRelations: (FoodCollection object) => {},
        getId: (FoodCollection object) => object.id,
        setId: (FoodCollection object, int id) {
          object.id = id;
        },
        objectToFB: (FoodCollection object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(12);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.productionDate.millisecondsSinceEpoch);
          fbb.addInt64(3, object.safeguardDay);
          fbb.addInt64(7, object.category);
          fbb.addInt64(9, object.expiredDate.millisecondsSinceEpoch);
          fbb.addInt64(10, object.reminderDays);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final productionDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final categoryParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final safeguardDayParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final expiredDateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));
          final reminderDaysParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final object = FoodCollection(
              name: nameParam,
              productionDate: productionDateParam,
              category: categoryParam,
              safeguardDay: safeguardDayParam,
              expiredDate: expiredDateParam,
              reminderDays: reminderDaysParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FoodCollection] entity fields to define ObjectBox queries.
class FoodCollection_ {
  /// See [FoodCollection.id].
  static final id =
      obx.QueryIntegerProperty<FoodCollection>(_entities[0].properties[0]);

  /// See [FoodCollection.name].
  static final name =
      obx.QueryStringProperty<FoodCollection>(_entities[0].properties[1]);

  /// See [FoodCollection.productionDate].
  static final productionDate =
      obx.QueryDateProperty<FoodCollection>(_entities[0].properties[2]);

  /// See [FoodCollection.safeguardDay].
  static final safeguardDay =
      obx.QueryIntegerProperty<FoodCollection>(_entities[0].properties[3]);

  /// See [FoodCollection.category].
  static final category =
      obx.QueryIntegerProperty<FoodCollection>(_entities[0].properties[4]);

  /// See [FoodCollection.expiredDate].
  static final expiredDate =
      obx.QueryDateProperty<FoodCollection>(_entities[0].properties[5]);

  /// See [FoodCollection.reminderDays].
  static final reminderDays =
      obx.QueryIntegerProperty<FoodCollection>(_entities[0].properties[6]);
}
